ft(coveralls-integration): add coveralls
atlp-rwanda/ateam-bn-backend pull request #2
Opened 2020-01-21 10:16 UTC by izabayogit

#### What does this PR do?
Integraate coveralls 
#### Description of Task to be completed?
- link coveralls with github repo
- integrate coveralls in codes
#### How should this be manually tested?
- clone git repo
- run npm test
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
- #170766077
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2020-01-21 10:30 UTC, KKDoddy commented
Looks good to me

2020-01-21 10:32 UTC, karengir commented
good work! I think there's no issue.

2020-01-22 11:54 UTC, karengir submitted a review, later dismissed
that's good, nothing to add.

2020-01-22 12:51 UTC, jajajaden01 commented
Looks good on my side.

2020-01-22 13:10 UTC, jajajaden01 submitted a review, later dismissed
Good job on my side

2020-01-22 15:08 UTC, KKDoddy submitted a review, later dismissed

2020-01-23 07:35 UTC, Nigorjeanluc submitted a review, later dismissed
It looks perfect to me

2020-01-24 20:49 UTC, Nigorjeanluc submitted a review, later dismissed

2020-01-25 14:55 UTC, karengir submitted a review, later dismissed

2020-01-26 07:43 UTC, key-joshua commented
Jonas should you correct your PR's description because there are some mistakes, Check well again !!

![jonas](https://user-images.githubusercontent.com/38179232/73132089-04fbdc00-401f-11ea-8c74-e9a6c6e83d4a.PNG)

The same-time your PR have conflicts which are needed to be resolved

![jonas conflict](https://user-images.githubusercontent.com/38179232/73132189-32955500-4020-11ea-891b-59c95b403d5b.PNG)

2020-01-27 07:01 UTC, jajajaden01 submitted a review, later dismissed

2020-01-27 09:54 UTC, jajajaden01 submitted a review, later dismissed

2020-01-27 09:56 UTC, Nigorjeanluc approved these changes

2020-01-27 14:11 UTC, YankyJayChris requested changes

2020-01-27 14:11 UTC, YankyJayChris commented on package.json
> -  "description": "We make company global travel and accommodation easy and convenient for the strong workforce of savvy members of staff, by leveraging the modern web.",
resolve this conflict

2020-01-27 14:11 UTC, YankyJayChris commented on package.json
> +>>>>>>> ft(coveralls-integration): add coveralls
resolve this conflict

2020-01-27 14:11 UTC, YankyJayChris commented on .travis.yml
> +  - node
work on this conflict

2020-01-28 06:52 UTC, Nigorjeanluc submitted a review, later dismissed

2020-01-28 12:33 UTC, KKDoddy submitted a review, later dismissed

2020-01-28 14:12 UTC, jajajaden01 submitted a review, later dismissed

2020-01-28 14:13 UTC, karengir submitted a review, later dismissed

2020-01-28 14:15 UTC, KKDoddy submitted a review, later dismissed

2020-01-28 16:07 UTC, Nigorjeanluc submitted a review, later dismissed

2020-01-28 17:02 UTC, YankyJayChris submitted a review, later dismissed

2020-01-29 11:33 UTC, jajajaden01 submitted a review, later dismissed

2020-01-29 11:40 UTC, karengir submitted a review, later dismissed

2020-01-29 12:55 UTC, key-joshua submitted a review, later dismissed

2020-01-30 16:37 UTC, luc-tuyishime commented on _BACKUP_83.gitignore
> +=======
Why these conflicts codes ??

2020-01-30 16:37 UTC, luc-tuyishime commented on .travis.yml
> +<<<<<<< HEAD
Resolve the conflicts properly.

2020-01-30 16:38 UTC, Nigorjeanluc submitted a review, later dismissed

2020-02-01 15:26 UTC, merged