(#170766098) Feature to create and delete comment on travel request
atlp-rwanda/ateam-bn-backend pull request #34
Opened 2020-02-11 07:57 UTC by jajajaden01

### What does this PR do?
- To create a trip comment, and able to delete that comment

### Description of the task to be completed
- create add and delete comment functionalities.
- testing both endpoints

### How should this be manually tested?
 - clone the repository, run the server locally then follow the instructions from the swagger documentation.

### What are the relevant pivotal tracker stories?
[#170766098](https://www.pivotaltracker.com/story/show/170766098)

2020-02-11 13:47 UTC, istafrica-dennw requested changes

2020-02-11 13:47 UTC, istafrica-dennw commented on server/controllers/TripCommentController.js
> +class TripController {
@jajajaden01 is this TripController? or commentController?

2020-02-11 13:47 UTC, istafrica-dennw commented on server/controllers/TripCommentController.js
> +    const savedComment = await commentHelper.saveComment(req.body);
can this line 36 fail? what happens when it does? to the code block 38 - 42 ?

2020-02-11 13:47 UTC, istafrica-dennw commented on server/middlewares/TripCommentValidator.js
> +  static NewComment(req, res, next) {
is this a function, a constant, a class ?. Make sure you are following best practices for function naming. Thank you

2020-02-12 07:57 UTC, jajajaden01 commented on server/controllers/TripCommentController.js
> +class TripController {
i'm going to correct that

2020-02-12 08:02 UTC, jajajaden01 commented on server/controllers/TripCommentController.js
> +    const savedComment = await commentHelper.saveComment(req.body);
If it fails, we get the server response (500) in a catch(){...}
in the route, there is a common function we use for try and catch

2020-02-12 08:03 UTC, jajajaden01 commented on server/middlewares/TripCommentValidator.js
> +  static NewComment(req, res, next) {
this was a mistake, I'm going to change it.

2020-02-15 08:47 UTC, closed without merging